
/**********************************************************************************************************************
 * \file HSSL_interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Libraries\iLLD\TC37A\Tricore\Hssl\Hssl\IfxHssl_Hssl.h"
#include "Libraries\iLLD\TC37A\Tricore\Dma\Dma\IfxDma_Dma.h"
#include "Libraries\iLLD\TC37A\Tricore\Scu\Std\IfxScuWdt.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
// used globally test
//  DMA channel handle
IfxDma_Dma_Channel chn;
IfxDma_Dma dma;

// Linked List storage

#define NUM_LINKED_LIST_ITEMS 3

// IMPORTANT: it has to be aligned to an 64bit address, otherwise DMA can't read it
//__attribute__((aligned(64))) Ifx_DMA_CH linkedList[NUM_LINKED_LIST_ITEMS];

// IMPORTANT: it has to be aligned to an bit address, otherwise DMA can't read it
IFX_ALIGN(256)
Ifx_DMA_CH linkedList[NUM_LINKED_LIST_ITEMS];
// transfer these values to channel 0 : HSSL_IWD0, HSSL_ICON0, HSSL_IRWA0 registers via linked lists
#define NUM_TRANSFERED_WORDS 3
// three write command queues with different data and to different addresses on slave
uint32 sourceBuffer[NUM_LINKED_LIST_ITEMS][NUM_TRANSFERED_WORDS] = {
    {0xC0CAC01A, 0xFF0A0000, 0x70000000},
    {0xBA5EBA11, 0xFF0A0000, 0x70000010},
    {0xDEADBEEF, 0xFF0A0000, 0x70000020}};

// three command queues to the same channel 0
const uint32 destinationAddresses[NUM_LINKED_LIST_ITEMS] = {
    (uint32)&HSSL0_IWD0,
    (uint32)&HSSL0_ICON0,
    (uint32)&HSSL0_IRWA0,
};
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void initDma(void)
{
    // build a linked list

    //  create module config
    IfxDma_Dma_Config dmaConfig;
    IfxDma_Dma_initModuleConfig(&dmaConfig, &MODULE_DMA);

    // initialize module
    IfxDma_Dma_initModule(&dma, &dmaConfig);

    // initial channel configuration
    IfxDma_Dma_ChannelConfig cfg;
    IfxDma_Dma_initChannelConfig(&cfg, &dma);

    // following settings are used by all transactions
    cfg.transferCount = NUM_TRANSFERED_WORDS;
    cfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest;
    cfg.moveSize = IfxDma_ChannelMoveSize_32bit;
    cfg.shadowControl = IfxDma_ChannelShadow_linkedList;

    // generate linked list items
    for (int i = 0; i < NUM_LINKED_LIST_ITEMS; ++i)
    {
        cfg.sourceAddress = IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), &sourceBuffer[i]);
        cfg.destinationAddress = destinationAddresses[i];

        // address to next transaction set
        cfg.shadowAddress = IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), (uint32)&linkedList[(i + 1) % NUM_LINKED_LIST_ITEMS]);

        // transfer first transaction set into DMA channel
        if (i == 0)
        {
            IfxDma_Dma_initChannel(&chn, &cfg);
        }

        // transfer into linked list storage
        IfxDma_Dma_initLinkedListEntry((void *)&linkedList[i], &cfg);

        if (i == 0)
        {
            // - trigger channel interrupt once the first transaction set has been loaded (again) into DMA channel
            linkedList[i].CHCSR.B.SIT = 1;
        }
        else
        {
            // - activate SCH (transaction request) for each entry, expect for the first one (linked list terminated here)
            linkedList[i].CHCSR.B.SCH = 1;
        }
    }
}

void startTransferDma(void)
{
    // clear service request flag
    (IfxDma_Dma_getSrcPointer(&chn))->B.CLRR = 1;
    // start linked list transaction
    IfxDma_Dma_startChannelTransaction(&chn);
    // wait for service request which is triggered at the end of linked list transfers
    while (!(IfxDma_Dma_getSrcPointer(&chn))->B.SRR)
        ;
}