/**********************************************************************************************************************
 * \file HSSL_interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "HSSL_interrupt.h"
#include "Libraries\iLLD\TC37A\Tricore\Hssl\Hssl\IfxHssl_Hssl.h"
#include "Libraries\iLLD\TC37A\Tricore\Hssl\Std\IfxHssl.h"
#include "Libraries\iLLD\TC37A\Tricore\_Impl\IfxSrc_cfg.h"
#include "Libraries\Infra\Sfr\TC37A\_Reg\IfxHsct_reg.h"



/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
//used globally test
const Ifx_HSCT *hsct = &MODULE_HSCT0;
const Ifx_HSSL *hssl = &MODULE_HSSL0;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void initHSCTinterrupt(void)
{
    //HSCT interrupts put after hsct module init
       
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_headerError);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_payloadError);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_commandError);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_speedModeSwitchError);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_interfaceControlFrameSend);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_pllLockLosterror);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_txTransferError);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_pingAnswerReceived);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_synchronizationFifoOverflow);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_synchronizationFifoUnderflow);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_UnsolicitedMessageReceived);
        IfxHssl_enableHsctInterruptFlag(hsct, IfxHssl_Hsct_InterruptSource_unsolicitedMessageSendFinished);

    // enable the HSCT interrupt
        IfxHssl_enableHsctInterrupt(hsct, IfxSrc_Tos_cpu0, 4);
}

void initHSSLinterrupt(void)
{

    //HSSL EXI interrupts put after hssl module init

        IfxHssl_enableHsslGlobalErrorInterruptFlag(hssl, IfxHssl_Hssl_EXIInterruptSource_busAccessError);
        IfxHssl_enableHsslGlobalErrorInterruptFlag(hssl, IfxHssl_Hssl_EXIInterruptSource_dataLengthError);
        IfxHssl_enableHsslGlobalErrorInterruptFlag(hssl, IfxHssl_Hssl_EXIInterruptSource_crcError);
        IfxHssl_enableHsslGlobalErrorInterruptFlag(hssl, IfxHssl_Hssl_EXIInterruptSource_channelNumberCodeError);
        IfxHssl_enableHsslGlobalErrorInterruptFlag(hssl, IfxHssl_Hssl_EXIInterruptSource_memoryAccessViolation);

    // enable the HSSL EXI interrupt (glob error interrupt)
        IfxHssl_enableHsslEXIInterrupt(hssl, IfxSrc_Tos_cpu0, 6);
}

void initHSSLChannelinterrupt(void)
{
    IfxHssl_ChannelId chanID[] =  {IfxHssl_ChannelId_0, IfxHssl_ChannelId_1, IfxHssl_ChannelId_2, IfxHssl_ChannelId_3};

     for(int i=0; i<4; ++i)
        {
        //HSSL ERR interrupts put after channel init
        IfxHssl_enableHsslChannelErrorInterruptFlag(hssl, chanID[i], IfxHssl_Hssl_ERRInterruptSource_transactionTagError);
        IfxHssl_enableHsslChannelErrorInterruptFlag(hssl, chanID[i], IfxHssl_Hssl_ERRInterruptSource_timeoutError);
        IfxHssl_enableHsslChannelErrorInterruptFlag(hssl, chanID[i], IfxHssl_Hssl_ERRInterruptSource_notAcknowledgeError);
        IfxHssl_enableHsslChannelErrorInterruptFlag(hssl, chanID[i], IfxHssl_Hssl_ERRInterruptSource_unexpectedError);

        // enable the HSSL ERR interrupt
        IfxHssl_enableHsslERRInterrupt(hssl, chanID[i], IfxSrc_Tos_cpu0, 8);
           
        }
   
}

 
